//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmersMarketplace.Application.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarmersMarketplace.Application.Resources.Exceptions.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied: Permission denied to modify data..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was not found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with email {0} was not found..
        /// </summary>
        internal static string AccountWithEmailNotFound {
            get {
                return ResourceManager.GetString("AccountWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was not found or email does not match the provided account..
        /// </summary>
        internal static string AccountWithIdEmailNotFound {
            get {
                return ResourceManager.GetString("AccountWithIdEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category was not found..
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with Id {0} was not found..
        /// </summary>
        internal static string CategoryWithIdNotFound {
            get {
                return ResourceManager.GetString("CategoryWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with name &apos;{0}&apos; was not found..
        /// </summary>
        internal static string CustomerWithNameNotFound {
            get {
                return ResourceManager.GetString("CustomerWithNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already associated with another account..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders documents was not deleted successful from Elasticsearch..
        /// </summary>
        internal static string ElasticsearchOrdersNotDeleted {
            get {
                return ResourceManager.GetString("ElasticsearchOrdersNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders documents was not uploaded successfully to Elasticsearch..
        /// </summary>
        internal static string ElasticsearchOrdersNotUpoaded {
            get {
                return ResourceManager.GetString("ElasticsearchOrdersNotUpoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products documents was not deleted successful from Elasticsearch..
        /// </summary>
        internal static string ElasticsearchProductsNotDeleted {
            get {
                return ResourceManager.GetString("ElasticsearchProductsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products documents was not uploaded successfully to Elasticsearch..
        /// </summary>
        internal static string ElasticsearchProductsNotLoaded {
            get {
                return ResourceManager.GetString("ElasticsearchProductsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already associated with another account..
        /// </summary>
        internal static string EmailIsAssociatedWithAnotherAccount {
            get {
                return ResourceManager.GetString("EmailIsAssociatedWithAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm was not found..
        /// </summary>
        internal static string FarmNotFound {
            get {
                return ResourceManager.GetString("FarmNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the file..
        /// </summary>
        internal static string FileCreatingError {
            get {
                return ResourceManager.GetString("FileCreatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with name {0} does not exist in directory {1}..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is incorrect..
        /// </summary>
        internal static string IncorrectRole {
            get {
                return ResourceManager.GetString("IncorrectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of image {0}. Acceptable formats: {1}..
        /// </summary>
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was not found..
        /// </summary>
        internal static string OrderNotExist {
            get {
                return ResourceManager.GetString("OrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders documents was not got successfully from Elasticsearch..
        /// </summary>
        internal static string OrdersNotGotSuccessfully {
            get {
                return ResourceManager.GetString("OrdersNotGotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm password do not match..
        /// </summary>
        internal static string PasswordNotMatchToConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordNotMatchToConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date of product cannot be later than receive date..
        /// </summary>
        internal static string ProductCreationDateIsLaterThanReceiveDate {
            get {
                return ResourceManager.GetString("ProductCreationDateIsLaterThanReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is used in existing orders..
        /// </summary>
        internal static string ProductIsUsed {
            get {
                return ResourceManager.GetString("ProductIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was not found..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products documents was not got successfully from Elasticsearch..
        /// </summary>
        internal static string ProductsNotGotSuccessfully {
            get {
                return ResourceManager.GetString("ProductsNotGotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file with name {0} was not found..
        /// </summary>
        internal static string SourceFileNotFound {
            get {
                return ResourceManager.GetString("SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic for month with id {0} was not found..
        /// </summary>
        internal static string StatisticWithIdNotExist {
            get {
                return ResourceManager.GetString("StatisticWithIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory does not belong to the category..
        /// </summary>
        internal static string SubcategoryNotBelongsToCategory {
            get {
                return ResourceManager.GetString("SubcategoryNotBelongsToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory was not found..
        /// </summary>
        internal static string SubcategoryNotFound {
            get {
                return ResourceManager.GetString("SubcategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory with Id {0} was not found..
        /// </summary>
        internal static string SubcategoryWithIdAndSubcategoryNotFound {
            get {
                return ResourceManager.GetString("SubcategoryWithIdAndSubcategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory with Id {0} was not found..
        /// </summary>
        internal static string SubcategoryWithIdNotFound {
            get {
                return ResourceManager.GetString("SubcategoryWithIdNotFound", resourceCulture);
            }
        }
    }
}
