//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForFarmers.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectForFarmers.Application.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with email {0} was not found..
        /// </summary>
        internal static string AccountWithEmailNotFound {
            get {
                return ResourceManager.GetString("AccountWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was not found or email does not match the provided account..
        /// </summary>
        internal static string AccountWithIdEmailNotFound {
            get {
                return ResourceManager.GetString("AccountWithIdEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with Id {0} was not found..
        /// </summary>
        internal static string AccountWithIdNotFound {
            get {
                return ResourceManager.GetString("AccountWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with Id {0} was not found..
        /// </summary>
        internal static string CategoryWithIdNotFound {
            get {
                return ResourceManager.GetString("CategoryWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected.
        /// </summary>
        internal static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer email.
        /// </summary>
        internal static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already associated with another account..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already associated with another account..
        /// </summary>
        internal static string EmailIsAssociatedWithAnotherAccount {
            get {
                return ResourceManager.GetString("EmailIsAssociatedWithAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm with Id {0} was not found..
        /// </summary>
        internal static string FarmWithIdNotExist {
            get {
                return ResourceManager.GetString("FarmWithIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm with Id {0} was not found..
        /// </summary>
        internal static string FarmWithIdNotFound {
            get {
                return ResourceManager.GetString("FarmWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with name {0} does not exist in directory {1}..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In delivery.
        /// </summary>
        internal static string InDelivery {
            get {
                return ResourceManager.GetString("InDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In processing.
        /// </summary>
        internal static string InProcessing {
            get {
                return ResourceManager.GetString("InProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of image {0}. Acceptable formats: {1}..
        /// </summary>
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order with id {0} was not found..
        /// </summary>
        internal static string OrderWithIdNotExist {
            get {
                return ResourceManager.GetString("OrderWithIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date of product cannot be later than receive date..
        /// </summary>
        internal static string ProductCreationDateIsLaterThanReceiveDate {
            get {
                return ResourceManager.GetString("ProductCreationDateIsLaterThanReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with id {0} was not found..
        /// </summary>
        internal static string ProductWithIdNotFound {
            get {
                return ResourceManager.GetString("ProductWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic for month with id {0} was not found..
        /// </summary>
        internal static string StatisticWithIdNotExist {
            get {
                return ResourceManager.GetString("StatisticWithIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory with Id {0} was not found..
        /// </summary>
        internal static string SubcategoryWithIdNotFound {
            get {
                return ResourceManager.GetString("SubcategoryWithIdNotFound", resourceCulture);
            }
        }
    }
}
